name: "❓ Question"
description: "질문 및 논의"
labels: ["question"]
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: 논의하고 싶은 주제와 현재 상황을 설명해 주세요.
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 논의 후 정리할 액션 아이템을 체크박스 형태로 작성해주세요.
      placeholder: 최대한 세분화 해서 적어주세요!
    validations:
      required: false
